import { readFileSync } from 'node:fs'
import { expect, it } from 'vitest'
import { makeTestApp } from './api-helpers.js'
import { resetDb, testDb } from './helpers.js'

it('retires credentials and unfinished work while preserving conversations, grants and old AI replies', async () => {
  await resetDb()
  const { app, loginAs } = await makeTestApp()
  try {
    const cookie = await loginAs('a@goldenlabs.dev')
    const owner = await testDb.user.findUniqueOrThrow({ where: { email: 'a@goldenlabs.dev' } })
    const peerCookie = await loginAs('b@goldenlabs.dev')
    const peer = await testDb.user.findUniqueOrThrow({ where: { email: 'b@goldenlabs.dev' } })
    const room = (await app.inject({ method: 'POST', url: '/api/conversations', headers: { cookie }, payload: { type: 'channel', title: '기록 보존', memberIds: [peer.id] } })).json()
    const bot = await testDb.user.create({ data: { email: 'old-bot@example.com', name: '과거 봇', isAgent: true } })
    // Legacy channel bots once had real memberships; these must no longer be offered as people.
    await testDb.conversationMember.create({ data: { conversationId: room.id, userId: bot.id } })
    const connection = await testDb.agentConnection.create({ data: { userId: bot.id, ownerId: owner.id, tokenHash: 'historical-hash', conversationId: room.id, expiresAt: new Date('2099-01-01') } })
    await testDb.user.update({ where: { id: owner.id }, data: { defaultAgentId: connection.id } })
    await testDb.agentConversationGrant.create({ data: { agentId: connection.id, conversationId: room.id } })
    await testDb.agentConversationExclusion.create({ data: { agentId: connection.id, conversationId: room.id } })
    const question = await testDb.message.create({ data: { conversationId: room.id, authorId: owner.id, body: '이전 질문' } })
    const answer = await testDb.message.create({ data: { conversationId: room.id, authorId: bot.id, body: '보존할 답변', replyToId: question.id } })
    const notice = await testDb.message.create({ data: { conversationId: room.id, authorId: owner.id, body: '과거 초대 공지', system: true } })
    const active = await testDb.agentRun.create({ data: { id: 'unfinished', agentId: connection.id, conversationId: room.id, requestedById: owner.id, prompt: question.body, questionMessageId: question.id } })
    const complete = await testDb.agentRun.create({ data: { id: 'complete', agentId: connection.id, conversationId: room.id, requestedById: owner.id, prompt: '완료된 질문', questionMessageId: 'old-question', resultMessageId: answer.id, status: 'COMPLETED', finishedAt: new Date('2026-09-10') } })
    const before = await testDb.message.findMany({ orderBy: { id: 'asc' } })
    const migration = readFileSync(new URL('../prisma/migrations/20260911080000_retire_ai_feature/migration.sql', import.meta.url), 'utf8')
    const statements = migration.replace(/^--.*$/gm, '').split(';').map(s => s.trim()).filter(s => s && !['BEGIN', 'COMMIT'].includes(s))
    const retire = () => testDb.$transaction(statements.map(sql => testDb.$executeRawUnsafe(sql)))
    await retire()
    const retired = await testDb.agentConnection.findUniqueOrThrow({ where: { id: connection.id } })
    expect(retired.revokedAt).not.toBeNull()
    expect(retired.tokenHash).toBe(connection.tokenHash)
    expect((await testDb.user.findUniqueOrThrow({ where: { id: owner.id } })).defaultAgentId).toBeNull()
    const ended = await testDb.agentRun.findUniqueOrThrow({ where: { id: active.id } })
    expect(ended).toMatchObject({ status: 'FAILED', errorCode: 'FEATURE_REMOVED' })
    expect(ended.finishedAt).not.toBeNull()
    expect(await testDb.agentRun.findUnique({ where: { id: complete.id } })).toEqual(complete)
    expect(await testDb.message.findMany({ orderBy: { id: 'asc' } })).toEqual(before)
    expect(await testDb.agentConversationGrant.count()).toBe(1)
    expect(await testDb.agentConversationExclusion.count()).toBe(1)
    await retire()
    expect(await testDb.agentConnection.findUnique({ where: { id: connection.id } })).toEqual(retired)
    expect(await testDb.agentRun.findUnique({ where: { id: active.id } })).toEqual(ended)

    const detail = (await app.inject({ url: `/api/conversations/${room.id}`, headers: { cookie: peerCookie } })).json()
    expect(detail.members.map((u: { id: string }) => u.id).sort()).toEqual([owner.id, peer.id].sort())
    const history = (await app.inject({ url: `/api/conversations/${room.id}/messages`, headers: { cookie: peerCookie } })).json()
    expect(history.items.find((m: { id: string }) => m.id === answer.id)).toMatchObject({ body: answer.body, author: { isAgent: true }, replyTo: { id: question.id } })
    expect(history.items.find((m: { id: string }) => m.id === notice.id)).toMatchObject({ system: true, body: notice.body })
    const post = (mentions: string[], body = '확인 부탁드립니다') => app.inject({ method: 'POST', url: `/api/conversations/${room.id}/messages`, headers: { cookie }, payload: { body, mentions } })
    expect((await post([bot.id])).statusCode).toBe(400)
    expect((await post([peer.id])).statusCode).toBe(201)
    expect((await post([], '@과거 봇 이제는 일반 텍스트')).statusCode).toBe(201)
    expect(await testDb.agentRun.count()).toBe(2)
    const activity = (await app.inject({ url: '/api/activity', headers: { cookie: peerCookie } })).json()
    expect(JSON.stringify(activity)).toContain('확인 부탁드립니다')
    expect((await app.inject({ method: 'POST', url: '/api/agent/messages', headers: { authorization: 'Bearer old-key' }, payload: { body: '차단' } })).statusCode).toBe(404)
  } finally { await app.close() }
})
